### ISSUE TITLE
Docstring standards in Slycot

### ISSUE THREAD

**Issue by bnavigator** [python-control/Slycot#100]
We have a bunch of different docstring styles used in the various definitions.

Some directly come from the `__doc__` property of the wrapper functions generated by f2py, recognizable by the `bounds` qualifier.
https://github.com/python-control/Slycot/blob/196e4ec6a5b77e612f8d2ee7082fe1e27a0dfb25/slycot/math.py#L104

Other functions use `shape()`
https://github.com/python-control/Slycot/blob/196e4ec6a5b77e612f8d2ee7082fe1e27a0dfb25/slycot/synthesis.py#L74

Sometimes we have blank space between the parameter definitions. Sometimes not.

What's your opinion on unifying this? Adhere to [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard)  and get closer to the documentation in numpy and scipy? Decide on a proper way to specify the shape? 

The array('d') is also not consistent with numpydoc, I guess.

Would also affect the math formulas.

**Comment by moorepants** [comment]
+1 to adopting numpydoc.

**Comment by bnavigator** [comment]
I used numpydoc in #103

**Comment by bnavigator** [comment]
With the recent PRs of @KybernetikJo, this has come a long way. Thank you!
