### ISSUE TITLE
test_mc01td_D failure on Windows

### ISSUE THREAD

**Issue by roryyorke** [python-control/Slycot#102]
See attached build log.  The failure is

```
======================================================================
FAIL: test_mc01td_D (test_mc.test_mc)
test_mc01td_D: test discrete option
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\rory\Documents\slycot\slycot\tests\test_mc.py", line 27, in test_mc01td_D
    self.assertEqual(stable, 1)
AssertionError: -1 != 1

----------------------------------------------------------------------
```

Build script:

```
set CONDA=%HOMEDRIVE%%HOMEPATH%\Miniconda3\condabin\conda.bat

echo %CONDA%

CALL %CONDA% --version
@if errorlevel 1 exit /b %ERRORLEVEL%

CALL %CONDA% activate base
@if errorlevel 1 exit /b %ERRORLEVEL%

CALL %CONDA% remove --yes --all --name build-slycot-py35
@if errorlevel 1 exit /b %ERRORLEVEL%

CALL %CONDA% create --quiet --yes --channel conda-forge --name build-slycot-py35 python=3.5 scikit-build flang numpy scipy
@if errorlevel 1 exit /b %ERRORLEVEL%

CALL %CONDA% activate build-slycot-py35
@if errorlevel 1 exit /b %ERRORLEVEL%

cd slycot
@if errorlevel 1 exit /b %ERRORLEVEL%

git describe --always --dirty
@if errorlevel 1 exit /b %ERRORLEVEL%

git status --ignored
@if errorlevel 1 exit /b %ERRORLEVEL%

@rem a hack; no f2py.exe
where f2py > %TMP%\F2PYPATH.txt
@if errorlevel 1 exit /b %ERRORLEVEL%
set /P F2PYPATH=< %TMP%\F2PYPATH.txt
@if errorlevel 1 exit /b %ERRORLEVEL%

python setup.py install -- -DF2PY_EXECUTABLE=%F2PYPATH%
@if errorlevel 1 exit /b %ERRORLEVEL%

cd slycot\tests
python -m unittest -v
```

build log: [slycot-win-build.txt](https://github.com/python-control/Slycot/files/4469287/slycot-win-build.txt)

**Comment by bnavigator** [comment]
Can you switch to `pytest` instead of old `unittest`?

**Comment by bnavigator** [comment]
https://github.com/python-control/Slycot/blob/ac53a0a744a73450daa23ef7bf8cfae5bcb01e5d/slycot/src/MC01TD.f#L53-L55

https://github.com/python-control/Slycot/blob/ac53a0a744a73450daa23ef7bf8cfae5bcb01e5d/slycot/src/math.pyf#L8

https://github.com/python-control/Slycot/blob/ac53a0a744a73450daa23ef7bf8cfae5bcb01e5d/slycot/math.py#L50-L51

https://github.com/python-control/Slycot/blob/ac53a0a744a73450daa23ef7bf8cfae5bcb01e5d/slycot/math.py#L58



https://github.com/python-control/Slycot/blob/ac53a0a744a73450daa23ef7bf8cfae5bcb01e5d/slycot/tests/test_mc.py#L14-L32

There is something wrong with the documented but nowhere defined mapping of `logical` to `int`. Does the Windows compiler map logical differently?

**Comment by bnavigator** [comment]
Some difference between (old) Intel compilers and gfortran: https://stackoverflow.com/questions/37293641/implicit-conversion-integer-logical-in-fortran-if-statement

**Comment by roryyorke** [comment]
If I comment out that assertion, the test passes.

We could check in `slycot.math.mc01td` for out[1] being non-zero, and make the output 0 or 1 (though I don't know if `.FALSE.` always maps to 0).  Or we could change the Fortran function to output an integer 0 or 1, instead of logical type.

"armflang" has `.TRUE.` set to -1, according to docs from mid-2018 [1]. I couldn't find anything else about flang conventions, neither via Google, nor `flang --help`.

Are we using `flang` in any of the Travis CI builds?

[1] https://armkeil.blob.core.windows.net/developer/Files/downloads/hpc/Arm-Fortran-Compiler-Reference-guide/Arm_Fortran_Compiler_Reference_101380_1840_00_en.pdf

**Comment by bnavigator** [comment]
I am already working on a PR. Stand by.
