### ISSUE TITLE
Consider switching CI to Github Workflows, include Windows

### ISSUE THREAD

**Issue by roryyorke** [python-control/Slycot#108]
Nothing for this release, but would it be worth to switch from Travis to Github Workflows and include Windows builds there? Possibly based on #80, although to me that seems a bit outdated by now.

_Originally posted by @bnavigator in https://github.com/python-control/Slycot/pull/101_

**Comment by bnavigator** [comment]
This will also be a good opportunity to adopt [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), which effectively means to drop the support for Python 2 and 3.5 now and 3.6 very soon.

**Comment by bnavigator** [comment]
I have been trying to prepare something in #140, but it is not finished yet.

Dropping Python 2 will also help to avoid workarounds like in #139.
