### ISSUE TITLE
PyPi release is older that those in this Github repo

### ISSUE THREAD

**Issue by moorepants** [python-control/Slycot#14]
PyPi has slycot 0.2.0 and it seems there are more tagged release commits here on Github. Would it be possible to push these to PyPi?

I just created a conda forge package for Slycot and would like to pull newer versions in via PyPi.

https://github.com/conda-forge/slycot-feedstock

**Comment by slivingston** [comment]
yes, thanks for the reminder.

In case it is useful in the interim, note that newer Slycot conda packages are already on the Anaconda site: https://anaconda.org/python-control/slycot

**Comment by murrayrm** [comment]
See also the discussion regarding different versions in issue #16.

**Comment by murrayrm** [comment]
@moorepants I had put slycot v0.3.0 onto PyPI and will eventually upload other versions.  If you have a chance, can you see whether you are able to build a new version of slycot on conda-forge.  If there are changes that are required, let me know and we can iterate.

**Comment by moorepants** [comment]
Slycot 0.3.0 is now on updated via conda-forge: https://anaconda.org/conda-forge/slycot

**Comment by moorepants** [comment]
Fixed with the 0.3.3 release.
