### ISSUE TITLE
Github workflow failures

### ISSUE THREAD

**Issue by roryyorke** [python-control/Slycot#144]
See https://github.com/python-control/Slycot/actions/runs/522944389

The failure is for Python 3.9, Generic BLAS.  The diagnostic is a low-level error that occurs during the python-control tests:
```
Windows fatal exception: code 0xc0000374
control\tests\xferfcn_test.py .......................................... [ 97%]
Windows fatal exception: code 0xc0000374

Current thread 0x00000730 (most recent call first):
  File "<string>", line 1 in <lambda>
  File "C:\Miniconda\envs\test-env\lib\tokenize.py", line 590 in _tokenize
  File "C:\Miniconda\envs\test-env\lib\site-packages\coverage\phystokens.py", line 147 in generate_tokens
```

Something similar happens in the Python 3.6 Generic BLAS, which is "FAILOK":

```
2021-01-30T08:10:18.8133613Z control\tests\nichols_test.py ..                                         [ 25%]
2021-01-30T08:10:19.1146867Z Windows fatal exception: code 0xc0000374
2021-01-30T08:10:19.1147451Z 
2021-01-30T08:10:19.1148013Z Current thread 0x00000bc4 (most recent call first):
2021-01-30T08:10:19.1150102Z   File "C:\Miniconda\envs\test-env\lib\site-packages\matplotlib\transforms.py", line 116 in __init__
```

Comparing the most recent 3.9 with the same build at https://github.com/bnavigator/Slycot/actions/runs/507101266, there are minor differences (different Github Windows env version, different git version, different build of python 3.9.1, pip 21.0, ruamel_yaml, different version of tzdata, matplotlib, coverage, pytest, urllilb.

The number of tests collected is different, probably due to changes in python-control:

Succesful build in PR:
```
============================= test session starts =============================
platform win32 -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: D:\a\Slycot\Slycot\python-control, configfile: setup.cfg
plugins: cov-2.11.1
collected 2339 items / 2 deselected / 2337 selected
```

Failed build in master:
```
============================= test session starts =============================
platform win32 -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: D:\a\Slycot\Slycot\python-control, configfile: setup.cfg
plugins: cov-2.11.1
collected 2351 items / 2 deselected / 2349 selected
```

For now I suggest we make Windows Python 3.9 Generic FAILOK too - we're passing Windows Python 3.9 with OpenBLAS and Intel10_64lp.

**Comment by bnavigator** [comment]
A rerun failed the same job but during a different test:
https://github.com/python-control/Slycot/runs/1797192943?check_suite_focus=true#step:8:208

Looks like a problem with the windows matplotlib package on conda to me. Possibly still caused by different BLAS libs for numpy and slycot.

I would say we FAILOK every windows build except unset Blas.
