### ISSUE TITLE
Confusion about which slycot repository is "official" / maintained

### ISSUE THREAD

**Issue by cknoll** [python-control/Slycot#16]
While dealing with a similar situation like in #15 I figured out that there are several slycot repos.

- https://github.com/avventi/Slycot
    - seems the "original one"
    - seems unmaintained (latest commit 2013-11 by @avventi )
- https://github.com/jgoppert/Slycot
    - linked from https://pypi.python.org/pypi/slycot/0.2.0 -> seems official
    - seems kind of inactive (latest commit 2016-03 by @jgoppert )
    - has useful hints on prerequisites for compiling from source
- https://github.com/python-control/Slycot
    - seems most relevant for users who need slycot as dependency of https://github.com/python-control/python-control (like me)
    - seems relatively active (latest commit 2017-05 by @roryyorke )

Maybe there are more relevant repos.

Are there rational reasons (other than historical ones) for that multitude of repos? At least for me that caused confusion.

**Comment by roryyorke** [comment]
python-control/slycot is about as "official" as it gets; it's certainly most alive, though development is slow.

As I recall python-control/Slycot was created with @jgoppert's agreement.  @avventi has not been active in years, assume he or she has lost interest.

Anything useful in @jgoppert's repo should be brought over here.

Regarding pip: I suspect many (most?) of us are using conda instead; an older (0.2.0) release of Slycot is available on conda-forge, and @cwrowley's channel, but only 0.2.0 in both cases (I think -- not that knowledgeable about conda):

  https://anaconda.org/conda-forge/slycot
  https://anaconda.org/cwrowley/slycot

**Comment by murrayrm** [comment]
It's on my list to do a new release of slycot (0.3.0) from python-control/slycot in the coming days/weeks and that should update the information on pypi. The plan is to also use that release to get a consistent version across github, pypi, and conda-forge, if I can figure out all of the dependencies.  I believe that I have the permissions required to do releases across all of the relevant platforms, but may need help from others who have contributed recipes, etc over the years.

I agree that if there is info in @jgoppert's repo that is useful, we should bring it here.

Will leave this issue open to track "consolidation" of everything into a single repo.

**Comment by roryyorke** [comment]
This is not too important, but you did release 0.3.0 about  a year ago on github, and @slivingston released 0.3.1 about two months later.  Neither version seems to have made it to conda-forge or PyPI.

**Comment by murrayrm** [comment]
I forgot about that!  I'll use the existing releases to see if I can get conda-forge and PyPI running, then push out 0.4.0.

**Comment by moorepants** [comment]
I created the conda-forge feedstock for slycot based on the latest release on PyPi:

https://github.com/conda-forge/slycot-feedstock

Anyone is welcome to add themselves as maintainers. For Python packages that can be released on PyPi, the typical setup is that the conda-forge recipe pulls the source code from an "official" PyPi release to build the conda-forge release. They typically consider the PyPi source tarballs to contain the essential build elements and to be more stable/canonical than other sources, e.g. a Github release or release on an arbitrary website.

**Comment by moorepants** [comment]
Also note that you can likely build cross-platform wheels for PyPi now, which would be convenient for those that do not use conda.

**Comment by murrayrm** [comment]
This issue is now resolved: python-control/slycot is the "official" repository and the current version (0.3.3) is pushed out to both PyPi and conda-forge (see issue #29 for deatils).
