### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by aditya-sengupta** [python-control/Slycot#162]
I'm using this package in a paper and I'm not sure how best to cite it - is there a convention that the project uses, or a source paper/original package it would be best to cite?

**Comment by murrayrm** [comment]
Here's what the APA has to say about citing software:

http://blog.apastyle.org/apastyle/2015/01/how-to-cite-software-in-apa-style.html

I think the citation might look something like:

[1] Slycot, Python wrapper for SLICOT [software] (2021). Retrieved from http://github.com/python-control/Slycot

You should also cite SLICOT if you are actually using it (this is required by the SLICOT licensing conditions).  For that, you can use the following paper: https://link.springer.com/chapter/10.1007/978-1-4612-0571-5_10

**Comment by aditya-sengupta** [comment]
Thank you!
