### ISSUE TITLE
Release v0.5.0

### ISSUE THREAD

**Issue by roryyorke** [python-control/Slycot#179]
- [x] Finalize release notes
  - [x] Check source tarball builds
  - [x] Tag
  - [x] upload to PyPI
  - ~~Add setup.py check for Numpy v1.23?~~ not needed, v1.23.1 fixes the problem
  - [x] ~~Notify conda-forge feedstock?~~ [conda-forge/slycot-feedstock update PR](https://github.com/conda-forge/slycot-feedstock/pull/50)

**Comment by roryyorke** [comment]
See https://github.com/python-control/Slycot/wiki/v0.5.0-release-notes-draft for draft release notes

**Comment by roryyorke** [comment]
On Numpy v1.23:

1. As I understand, we should in principle be able to build against (i.e., with) Numpy v1.22, and still install with v1.23.  I'm not 100% sure how to test that -- I guess I could build a wheel and test?

2. Is it worth adding detection of Numpy v1.23 to warn anyone trying to build Slycot with that version?

3. How do we handle this build problem in conda-forge?  Does that build against a very old version of Numpy *anyway* ?

**Comment by roryyorke** [comment]
Oh, Numpy v1.23.1 sorts out the build issue: https://github.com/numpy/numpy/releases/tag/v1.23.1, so that's at least not a worry.  I'm not having luck with `python -m build` yet, though.

**Comment by roryyorke** [comment]
I think my build problems are due to https://github.com/scikit-build/scikit-build/issues/524.

**Comment by bnavigator** [comment]
> On Numpy v1.23:

> 1. As I understand, we should in principle be able to build against (i.e., with) Numpy v1.22, and still install with v1.23.  I'm not 100% sure how to test that -- I guess I could build a wheel and test?

This was the case in the current CI until 1.23.1 came out;

https://github.com/python-control/Slycot/runs/7133906655?check_suite_focus=true#step:6:110

https://github.com/python-control/Slycot/runs/7134112685?check_suite_focus=true#step:8:34

> 2. Is it worth adding detection of Numpy v1.23 to warn anyone trying to build Slycot with that version?

The pyproject.toml prevents a (PEP517 based) build with 1.23.0, that should be enough.

> 3. How do we handle this build problem in conda-forge?  Does that build against a very old version of Numpy _anyway_ ?

It's the same mechanism: `build and host: numpy!=1.23.0`, `run: {{ pin_compatible('numpy') }}`.

**Comment by bnavigator** [comment]
> I think my build problems are due to [scikit-build/scikit-build#524](https://github.com/scikit-build/scikit-build/issues/524).

I just tried `python -m build .` with current master, and it sucessfully built a wheel with in an isolated build venv with numpy 1.23.1. What's your error message?

**Comment by bnavigator** [comment]
That's indeed strange. The build module normally sets up an isolated build environment which does not give access to the system sitelib.

**Comment by roryyorke** [comment]
I was running `python3 -m build .` from the base (system) environment.  I haven't installed `build` for Python2.

I'm reasonably sure https://github.com/scikit-build/scikit-build/issues/524 is still relevant; I could reproduce the build problem with `setup.py bdist_wheel` in a venv.  Also, from the description of `find_path`, one can see that the "PATHS" argument to find_path is consulted nearly last.  A simple fix for scikit-build would be to use the HINTS argument, which is intended for introspectively-discovered paths.  (This doesn't fix FindPython use, which looks like it should be much nicer.)

**Comment by roryyorke** [comment]
Thanks for the updates to the release notes.  I forgot to add a list of contributors, which I'll do now---then I think that's done?

**Comment by roryyorke** [comment]
All done!
