### ISSUE TITLE
Running `td04ad` in Google Colab causes the runtime to crash.

### ISSUE THREAD

**Issue by knttnk** [python-control/Slycot#215]
In [Google Colaboratory](https://colab.research.google.com/), running the following code causes the runtime to crash.
```python
!pip install slycot
import numpy as np
from slycot import td04ad

denorder = np.array([3])
num = np.array([[[0., 0.25, 0.5, 0.75]]])
den = np.array([[1., 1.25, 1.5, 1.75]])

ssout = td04ad(
    'C',
    1, 1,
    denorder, den, num,
    tol=0,
)
```

Produces no error messages, but this is runtime log:
|Timestamp|Level|Message|
|---|---|---|
|Sep 22, 2023, 5:40:30 AM|WARNING|WARNING:root:kernel dc25aa39-741b-4b71-ba36-3aaa34d7cdcb restarted|
|Sep 22, 2023, 5:40:30 AM|INFO|KernelRestarter: restarting kernel \(1/5\), keep random ports|
|Sep 22, 2023, 5:40:29 AM|WARNING|Intel MKL FATAL ERROR: Cannot load libmkl\_avx2\.so or libmkl\_def\.so\.|
|Sep 22, 2023, 5:40:29 AM|WARNING|INTEL MKL ERROR: /lib/x86\_64-linux-gnu/libmkl\_avx2\.so: undefined symbol: mkl\_sparse\_optimize\_bsr\_trsm\_i8\.|
|Sep 22, 2023, 5:37:12 AM|INFO|Kernel started: dc25aa39-741b-4b71-ba36-3aaa34d7cdcb, name: python3|

**Comment by roryyorke** [comment]
I don't think the undefined MKL symbol can be directly caused by Slycot.  I know nothing about Google Colab, but I think you're going to have to investigate the Slycot build, what BLAS/LAPACK gets linked, and how that compares to what Numpy links to.  (This is a bit of a guess - not really sure what could cause this error.)

If `conda` or `mamba` are available on Google Colab, I suggest using them.

**Comment by bnavigator** [comment]
> ```python
> !pip install slycot
> ```

I guess this command takes some time in the environment because it means that slycot is compiled on the fly. Try at least a `-v` flag to see what happens. Very likely MKL headers are found somewhere but the corresponding libraries are not installed.

**Comment by bnavigator** [comment]
... which is the same advice a gave you last time: #183

**Comment by bnavigator** [comment]
This works for me:

```python
!apt-get install gfortran cmake --fix-missing
!apt-get install libblas-dev liblapack-dev

import os
os.environ['BLA_VENDOR']="Generic"
!echo Using $$BLA_VENDOR BLAS implementation

!pip install -v slycot
```

```python
import numpy as np
from slycot import td04ad

denorder = np.array([3])
num = np.array([[[0., 0.25, 0.5, 0.75]]])
den = np.array([[1., 1.25, 1.5, 1.75]])

ssout = td04ad(
    'C',
    1, 1,
    denorder, den, num,
    tol=0,
)
```

**Comment by knttnk** [comment]
Thank you! It works for me.
