### ISSUE TITLE
`test_xerbla_override` fails on "pure" conda-forge install

### ISSUE THREAD

**Issue by roryyorke** [python-control/Slycot#218]
Environment created with `mamba create -n slycot-dev python compilers numpy "setuptools>=45" "setuptools_scm>=6.3" "scikit-build>=0.14.1" cmake scipy pytest ipython matplotlib` (see below for exported environment).

System is Ubuntu 20.04 x86_64.

Tested with https://github.com/python-control/Slycot/commit/9485d94aaae2221dd82ee0bd7c66e28d610e390f

This *didn't* happen with when `defaults` channel was in .condarc.

[buildlog.txt](https://github.com/python-control/Slycot/files/12841232/buildlog.txt)
[conda-env.txt](https://github.com/python-control/Slycot/files/12841233/conda-env.txt)
[pytest-output.txt](https://github.com/python-control/Slycot/files/12841234/pytest-output.txt)

I speculate that this is something to do with the specific blas / lapack libraries installed.

I see this in buildlog.txt:

```
In: /home/rory/src/slycot/slycot/src/_wrapper.pyf:_wrapper:unknown_interface:xerbla
```

**Comment by bnavigator** [comment]
```
E               subprocess.CalledProcessError: Command '['/home/rory/mambaforge/envs/slycot-dev/bin/python3.11', '-c', '\nimport sys\nsys.path.pop(0)  # do not import from current directory (\'\')\nfrom slycot._wrapper import __file__, ab08nd\nprint(__file__)\n# equil=\'X\' is invalid\nout = ab08nd(1, 1, 1, [1], [1], [1], [1], equil=\'X\')\nprint("INFO={}".format(out[-1]))\n']' returned non-zero exit status 1.

../../mambaforge/envs/slycot-dev/lib/python3.11/subprocess.py:571: CalledProcessError

During handling of the above exception, another exception occurred:

    def test_xerbla_override():
        """Test that Fortran routines calling XERBLA do not print to stdout."""
    
        try:
            out = subprocess.check_output([sys.executable, '-c', CODE],
                                           stderr=subprocess.STDOUT,
                                           universal_newlines=True)
        except subprocess.CalledProcessError as cpe:
>           raise RuntimeError("Trying to call _wrapper.ab08nd() failed with "
                               "returncode {}.\n"
                               "Captured STDOUT: \n {}\n"
                               "Captured STDERR: \n {}\n"
                               "".format(cpe.returncode, cpe.stdout, cpe.stderr))
E           RuntimeError: Trying to call _wrapper.ab08nd() failed with returncode 1.
E           Captured STDOUT: 
E            Traceback (most recent call last):
E             File "<string>", line 4, in <module>
E           ModuleNotFoundError: No module named 'slycot'
E           
E           Captured STDERR: 
E            None
```

This does not look like a xerbla error, but like an error in the test environment. Why does `/home/rory/mambaforge/envs/slycot-dev/bin/python3.11` not find slycot when it's supposed to be the same interpreter as you call pytest from? And that one obviously found slycot for the other tests.

Until I find a better explanation, I blame stupid conda.

**Comment by roryyorke** [comment]
I found the better explanation: I missed the `conda develop .` step.  Sorry for the noise!
