### ISSUE TITLE
Slycot Installation Issue

### ISSUE THREAD

**Issue by A622266** [python-control/Slycot#224]
Hello

I'm having difficulty installing slycot on my system.  My purpose is to use with python-control.
My system is Ubuntu 22.04.
I am working in a virtual environment.   I have the following installed in the virtual environment in relevant part:
Python==3.10.12
Numpy==1.21.5
scikit-build==0.17.6

On my system (using sudo apt-get install), I have installed:
cmake 3.25.1-12ppa1~ubuntu22.04
gcc 4:11.2.0-1ubuntu1
gfortran 4:11.2.0-1ubuntu1
liblapack-dev 3.10.0-2ubuntu1
liblapacke-dev 3.10.0-2ubuntu1

I believe this is all the prerequisites from the documentation.  I then try in the virtual environment:
pip install slycot

The attached log file indicates some kind of an error with CMake.  
I see in the documentation the recommendation to set BLA_VENDOR=generic.  I tried:
export BLA_VENDOR=generic
And I can see it when I run 'env' to check the environment variables.  Also there I see:
BLAS_H=/usr/include/x86_64-linux-gnu/cblas.h

Can anyone give advice for next steps?

Thanks
Andy

[log.txt](https://github.com/python-control/Slycot/files/13342226/log.txt)

**Comment by bnavigator** [comment]
Looks like your python headers in `/usr/include/python3.10` do not match the interpreter version of your venv.

Try to build a wheel with the plain ubuntu python, not activating any venv. Install the built wheel into the venv afterwards:

```
sudo apt install python3-wheel
/usr/bin/python3 -m pip wheel -v slycot
/home/andrew/github/classd-ls/venv/bin/python3 -m pip install ./slycot-0.5.4*.whl
```

**Comment by A622266** [comment]
Yes with your help I was successful.  For some reason, the built version of slycot was not 0.5.4, but rather 0.5.0.
slycot-0.5.0-cp310-cp310-linux_x86_64.whl
But it does appear to be working.  Thanks for your help.

Regards
Andy
