### ISSUE TITLE
Missing test_X.py files in slycot/tests/CMakeLists.txt

### ISSUE THREAD

**Issue by KybernetikJo** [python-control/Slycot#228]
Currently, there are 20 test_X.py files in the "slycot/tests" folder, but only 17 in the "slycot/tests/CMakeLists.txt".
https://github.com/python-control/Slycot/blob/master/slycot/tests/CMakeLists.txt

It made no difference whether all 20 or 17 files were listed in CMakeLists.txt.

pytest --pyargs executed all tests.

What is the slycot/tests/CMakeLists.txt file needed for?

**Comment by bnavigator** [comment]
Good catch. The `install(FILES <pythonfiles> ...)` are redundant and ignored/overruled by scikit-build.
