### ISSUE TITLE
New release with binaries on Conda Forge

### ISSUE THREAD

**Issue by saasaa** [python-control/Slycot#233]
Hello and thank you for maintaining this library.

Would it be possible to build and upload new binaries to Conda Forge? 
I have a couple of Windows Users who want to use my recent pull [request](https://github.com/python-control/Slycot/pull/214) , but unfortunately cannot be bothered to build slycot manually.

Thank you and all the best

**Comment by bnavigator** [comment]
Yes, it's long overdue. See #204

**Comment by bnavigator** [comment]
I have cut a release for Slycot 0.6. Packages should appear on conda-forge soon.
