### ISSUE TITLE
Push release 0.3.3 to conda-forge, PyPI

### ISSUE THREAD

**Issue by murrayrm** [python-control/Slycot#29]
Now that [release 0.3.3](https://github.com/python-control/Slycot/releases/tag/v0.3.3) is done, we need to push `slycot-0.3.3` out to conda-forge and PyPI.

@moorepants Can you generate a new build on conda-forge?
  * Note that there is a PR on the conda-forge feedstock that needs to be merged first, I think
  * Is it possible to enable a Windows build as well?

@jgoppert Can you update PyPI?

Also, if someone can summarize the instructions for what needs to be done to generate these releases, then I will create a page on the wiki with this information to make it easier to do this in the future.

**Comment by moorepants** [comment]
This needs to be merged first: https://github.com/conda-forge/slycot-feedstock/pull/4. Working on it.

**Comment by moorepants** [comment]
As far as I know there is no Fortran compiler available for windows in the conda forge infrastructure, but some major updates to conda forge were recently released. Maybe there is now an option.

**Comment by murrayrm** [comment]
I've pushed v0.3.3 out to PyPI (and confirmed I was able to install locally using pip) and I've submitted a pull request on conda-forge for version 0.3.3.  The linux compilations where successful; still waiting on the MacOS version.

**Comment by murrayrm** [comment]
Slycot 0.3.3 is now available on conda-forge.  Before closing this issue, need to figure out what is going on in [python-control/#217](https://github.com/python-control/python-control/issues/217).

**Comment by murrayrm** [comment]
[Python-control/#217](https://github.com/python-control/python-control/issues/217) is not a slycot issue per se (see comments there), so closing this out.
