### ISSUE TITLE
Installation of slycot on Win64 failed

### ISSUE THREAD

**Issue by bjfurman** [python-control/Slycot#37]
Attempting to install slycot following instructions given at: https://anaconda.org/repa/slycot AND https://github.com/python-control/slycot fails. Both approaches indicate 'PackagesNotFoundError':

``C:\WINDOWS\system32>conda install -c repa/label/test slycot
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - slycot

Current channels:

  - https://conda.anaconda.org/repa/label/test/win-64
  - https://conda.anaconda.org/repa/label/test/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.``

Is there a workaround?

**Comment by murrayrm** [comment]
We have been struggling with getting a Windows build working.  See PR #33 for some information from @repagh on what he has been trying (but this is not fully debugged yet).

We can perhaps use this issue to figure out how to handle windows builds of `slycot`.

**Comment by repagh** [comment]
There should be new packages now. 

conda install -c repa slycot 

works for me.

**Comment by bjfurman** [comment]
I still get a fail to solve the environment:

`C:\WINDOWS\system32>conda install -c repa slycot
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - slycot
  - libflang
  - slycot
  - openblas

Current channels:

  - https://conda.anaconda.org/repa/win-64
  - https://conda.anaconda.org/repa/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

**Comment by repagh** [comment]
You do need the conda-forge channel too;
`conda config --append channels conda-forge`

**Comment by bjfurman** [comment]
Brilliant! Appending the conda-forge channel was the step that I was missing. Thank you!
