### ISSUE TITLE
Fix Coveralls URL in README.md

### ISSUE THREAD

**Issue by roryyorke** [python-control/Slycot#44]
The coveralls link is broken; it's not just the case of "Slycot" in the URL, since both https://coveralls.io/r/python-control/slycot (the current URL in README.md) and https://coveralls.io/r/python-control/Slycot give 404s.

I don't know much about coveralls; is python-control/Slycot registered properly?  Are we missing a step in the Travis CI build?

We could just remove this badge and URL.

**Comment by kangwonlee** [comment]
* If I may; briefly checked and noticed its (sort-of) [upper level link](https://coveralls.io/github/python-control/) lists [python-control](https://github.com/python-control/python-control) only.
* IMHO, one of https://github.com/orgs/python-control/people could take a look at the [upper level link](https://coveralls.io/github/python-control/)?
* Please let me know any possible improvements

**Comment by murrayrm** [comment]
Good catch @kangwonlee.  I've added `slycot` to the list of repositories in the `python-control` account on Coveralls.  As soon as there is another build, that should fix things up.

**Comment by kangwonlee** [comment]
* I could see that https://coveralls.io/github/python-control/Slycot is now available
* Any further action necessary?

**Comment by roryyorke** [comment]
Thanks @kangwonlee , I'd forgotten this.  Something is still not quite right, since coveralls says "no data" for all those builds.

We probably need to tweak the Travis build to find the results of the "Slycot/runtests.py" command.

**Comment by roryyorke** [comment]
Fixed in #97 and #101.
