### ISSUE TITLE
setup doesn't recognize the command 'config_fc'

### ISSUE THREAD

**Issue by crvs** [python-control/Slycot#47]
The current setup.py configuration seems to have broken config_fc command.

**Comment by repagh** [comment]
The build system now uses scikit-build

Specifying the Fortran compiler can be done by setting an environment variable FC
Linux/Mac:  export FC=/path/to/my/fortran
Windows: set FC=C:\path\to\my\fortran.exe

Does that answer your question/solve your problem?

**Comment by crvs** [comment]
Thanks! it did compile like this and while there wasn't an error in the compilation it failed to load.
In the end I was able to compile it properly by  checking out  a previous release and compiling as the README suggests with the --arch="-march=x86-64" ... or something like that.
I guess that the README should be updated to mirror the changes then.

**Comment by roryyorke** [comment]
Fixed in #52
