### ISSUE TITLE
About compiling from source

### ISSUE THREAD

**Issue by joaoantoniocardoso** [python-control/Slycot#54]
I would like to point out that if fortran was an issue to compile from the sources, note that it is compiling just fine using [kitware/ninja](https://github.com/Kitware/ninja). :+1: 

Thanks!

**Comment by roryyorke** [comment]
Thanks - for posterity, and in the hopes that of assisting search engines find this: as of early 2019, ninja had some problems building Fortran, and Kitware's patches fixed this (Kitware are the authors of CMake, and ninja is one of the build tools CMake generates build files for.)
