### ISSUE TITLE
Drop Python 2.6

### ISSUE THREAD

**Issue by moorepants** [python-control/Slycot#59]
setup.py has:

```
if sys.version_info[:2] < (2, 6) or (3, 0) <= sys.version_info[0:2] < (3, 2):
    raise RuntimeError("Python version 2.6, 2.7 or >= 3.2 required.")
```

Seems like we should drop 2.6 and any references to it.

**Comment by roryyorke** [comment]
We could also remove 3.2, 3.3, and 3.4 here -- 3.4 isn't strictly end-of-life, but we don't test against it.  numpy 1.16 requires 2.7, or 3.4 or newer.

I suppose at some not-too-distant point we'll also drop 2.7.  Does conda-forge have a date from which 2.7 won't be supported, or will it be handled on a package-by-package basis?

**Comment by moorepants** [comment]
I'm not quite sure how conda forge will handle dropping py27. I can imagine there will be a lot of grumbling everywhere about the upcoming Jan 2020 drop date from the PSF. Maybe play that one by ear. Dropping 2.6, 3.2-3.4 sounds like a good idea.
