### ISSUE TITLE
Install from PyPI fails - 0.3.4.0

### ISSUE THREAD

**Issue by jgspiro** [python-control/Slycot#61]
In a clean python environment, slycot does not install, because of a missing dependency (skbuild).

```
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-er4161h2/slycot/setup.py", line 8, in <module>
        from skbuild import setup
    ImportError: No module named 'skbuild'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-er4161h2/slycot/
```

Tried with python 2.7 and 3.5

This is not the case with previous version 0.3.3

**Comment by jgspiro** [comment]
Both `scikit-build` and `numpy` need to be installed manually to be able to install slycot. ( Linux, clean python virtual env.)

**Comment by ilayn** [comment]
You need to have `scikit-build` package installed.
