### ISSUE TITLE
Release 0.3.5

### ISSUE THREAD

**Issue by roryyorke** [python-control/Slycot#70]
I'd like to release current master, or something close to it, as 0.3.5.  Our current PyPI release, 0.3.4, is arguably broken: `pip install slycot` doesn't work on Linux systems (I suspect also not on OSX), but 0.3.5 should fix that.

@murrayrm, could you please test the build on OSX?  Something like `pip install git+https://github.com/python-control/Slycot` in a clean virtual-env (no numpy, no scikit-build, up-to-date pip) should be sufficient.

AFAIK, conda builds are still OK.  @repagh, @moorepants, please let me know if there is anything conda-related that must be done.

**Comment by bnavigator** [comment]
Current master builds fine on the OpenSUSE build system now, thanks for the fixes!
https://build.opensuse.org/package/show/home:bnavigator/python-slycot

**Comment by moorepants** [comment]
One notes is that we should change build.sh and bld.bat in the conda-forge feedstock to the recommended:

```
python -m pip install --no-deps --ignore-installed .
```

Then pip install-ability will be checked downstream. You can do something similar on the Travis builds here.

**Comment by roryyorke** [comment]
@moorepants thanks, that's a good idea.  From googling (e.g. [conda-build docs](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html) and [a conda-forge tutorial](https://ocefpaf.github.io/2018-SciPy-python-packaging-tutorial/#/hands-on-exercise)) it looks like one should add pip to the list of `host` requirements in that case.

Is there any somewhat-authoritative source for this recommendation?   Would like to put it in the commit log.

**Comment by roryyorke** [comment]
[current conda-forge docs](http://conda-forge.org/docs/maintainer/adding_pkgs.html#use-pip) recommend `"{{ PYTHON }} -m pip install . --no-deps -vv"`

The "--ignore" makes sense, so I'll keep that; I'll add -vv.

**Comment by moorepants** [comment]
I'd use the conda-forge docs as the primary source for the conda-forge feedstock and the conda-build for anything you are doing in this repo. Conda-forge has some requirements that are specific to their build infrastructure.

**Comment by moorepants** [comment]
This is what I was looking for originally:

```
{ PYTHON }} -m pip install . --no-deps -vv
```

I found `python -m pip install --no-deps --ignore-installed .` instead. The docs are too confusing! Go with the one you found.

**Comment by roryyorke** [comment]
> I'd use the conda-forge docs as the primary source for the conda-forge feedstock and the conda-build for anything you are doing in this repo.

My understanding of why we're doing conda-builds at all in our CI is as early-warning of problems for conda-forge, so we might as well follow conda-forge practices.

Speaking of which, is there any way to use the conda-forge recipe in the Slycot, rather than using our own?  It feels like we're duplicating effort i.t.o. of conda-build recipe maintenance otherwise.

**Comment by moorepants** [comment]
The conda recipes in the Slycot repo predated me building it on conda forge. I'm not sure I've ever looked at them. If you want to build the conda forge recipes before a release, then you may have to set up a similar CI configuration. It is possible to have conda forge build prereleases from a sub-channel which is another way to trigger a conda forge build on their system and avoiding people installing a new release.

**Comment by murrayrm** [comment]
Report on OSX build:

* Trying to build from a *completely* clean environment (Python 3.7, using conda) fails because of the lack of a FORTRAN compiler.

* After installing a FORTRAN compiler (using `conda install gcc`), installation was successful.  Output attached below.

```
(slycot-test) nemaya:~ murray$ pip install git+https://github.com/python-control/Slycot
Collecting git+https://github.com/python-control/Slycot
  Cloning https://github.com/python-control/Slycot to /private/var/folders/mf/mg10yhgs0_j0wr03c7vw0hnc0000gn/T/pip-req-build-n9pvsf1m
  Running command git clone -q https://github.com/python-control/Slycot /private/var/folders/mf/mg10yhgs0_j0wr03c7vw0hnc0000gn/T/pip-req-build-n9pvsf1m
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy (from slycot==0.3.4.23)
  Using cached https://files.pythonhosted.org/packages/6b/be/608b7f72b851472388eafc010a5d46dae5d41610d0ac5df4c98c2ed1b865/numpy-1.16.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Building wheels for collected packages: slycot
  Building wheel for slycot (PEP 517) ... done
  Stored in directory: /private/var/folders/mf/mg10yhgs0_j0wr03c7vw0hnc0000gn/T/pip-ephem-wheel-cache-1rfdji3s/wheels/56/5f/0e/f52a52e6f7bb57a8d00c45721e2ed8b8f461c936f0f2d2d000
Successfully built slycot
Installing collected packages: numpy, slycot
Successfully installed numpy-1.16.4 slycot-0.3.4.23
(slycot-test) nemaya:~ murray$ pwd
/Users/murray
(slycot-test) nemaya:~ murray$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import slycot
>>> slycot.__version__
'0.3.4.23.git2894c98'
```

**Comment by roryyorke** [comment]
@murrayrm great, thank you.  [0.3.5 is tagged](https://github.com/python-control/Slycot/releases/tag/v0.3.5) - could you please publish to PyPI?

**Comment by murrayrm** [comment]
Uploaded.  SHA256 has is `cad98d5ea4f0a034cf398c39189f587620a0b03f1d4b71e77cd622a327f13adf`
