### ISSUE TITLE
Travis OSX builds are failing

### ISSUE THREAD

**Issue by roryyorke** [python-control/Slycot#76]
The error is `ImportError: numpy.core.multiarray failed to import`, which suggests to me it's our build setup that's wrong, not Slycot itself.  This could be the Travis setup, the conda recipe, or perhaps CMakeLists.txt or setup.py.

This issue would best be handled by somebody with an OSX system.

**Comment by rabraker** [comment]
For whatever it's worth, I've seen this error before in other projects when I tried to load a C extension module in a different version of python than the module was linked against during compilation. If anybody knows where the _module.so gets installed on macOS, we could confirm my theory by running

```
ldd /path/to/_module.dylib
```
in travis before the unittests are run. Or whatever the mac equivalent of ldd is...

**Comment by kangwonlee** [comment]
I tried with GitHub Workflows and the OSX results are available [here](https://github.com/kangwonlee/Slycot/runs/215921809).
Hope this helps.

**Comment by repagh** [comment]
See PR #92 
Conda compilers and libraries require a specific OSX SDK.

**Comment by bnavigator** [comment]
The osx builds on https://github.com/conda-forge/slycot-feedstock succeed. But they have a vastly different OSX environment than Travis CI. Their Azure pipelines include the correct OSX SDK and link to it.

Can we ditch the OSX conda builds on Travis here? Maybe mimic the conda-forge feedstock to check if conda packages can still be built (for all supported operating systems!), but trying to get Travis to work seems not very relevant.

**Comment by bnavigator** [comment]
See also the Travis jobs for bnavigator/Slycot#1

**Comment by bnavigator** [comment]
fixed by #93

**Comment by roryyorke** [comment]
Thanks!
