### ISSUE TITLE
Wrapper for functions related to periodic Schur decomposition

### ISSUE THREAD

**Issue by RRiva** [python-control/Slycot#86]
Dear Slycot support,

SLICOT is probably the only library with an implementation of the periodic Schur decomposition, which is very useful in the analysis of Linear Time-Periodic systems. The main function is `MB03WD`, which needs `MB03VD` and probably also `MB03XP` and `MB03YD`. Could you please add a wrapper for these subroutines?

Thank you very much 😊 

Best regards,
Riccardo Riva

**Comment by bnavigator** [comment]
Is #88 what you are looking for? `MB03WX` is used in the documentation example, but the unittest I built based on it succeeds without it.

`MB03XP` and it's auxiliary routines could be added, too. Can't promise if I find time in the next few days though.

**Comment by RRiva** [comment]
Hi Ben, yes it is! It's nice to see how short the test becomes when it's written in python. Also declaring `W` as a complex array is a good idea.

I only needed `MB03WD`, so you can skip the other routines.

Thanks a lot 😊

**Comment by roryyorke** [comment]
Fixed in #88.
