### ISSUE TITLE
simplify version labeling and Git commit hash extraction

### ISSUE THREAD

**Issue by slivingston** [python-control/Slycot#9]
Following comments on <https://github.com/python-control/Slycot/commit/5d21c69f034550f3b475c63404c806b3322bae52>, we should simplify the code in [setup.py](https://github.com/python-control/Slycot/blob/5d21c69f034550f3b475c63404c806b3322bae52/setup.py) that generates the version string that labels an installation of Slycot. This is somewhat nontrivial because, for non-release commits, it is useful to include the commit hash in the version string.

Two proposals have been made thus far:

1. use [versioneer](https://github.com/warner/python-versioneer) (https://github.com/python-control/Slycot/commit/5d21c69f034550f3b475c63404c806b3322bae52)
2. use [make_version.py](https://github.com/python-control/python-control/blob/5ab74cfbc15dd249ba5bc88a30f2957e05bb2984/make_version.py) from `python-control` (https://github.com/python-control/Slycot/commit/5d21c69f034550f3b475c63404c806b3322bae52#commitcomment-20885735)

Interestingly, this is a perennial issue in the development of Python packages that have change history tracked in Git. Slycot requires compilation of FORTRAN code, so NumPy should be a good first reference regarding labeling built binary packages.

**Comment by roryyorke** [comment]
@repagh I believe you've solved this with [GIT_DESCRIBE_TAG](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html?highlight=GIT_DESCRIBE_TAG#git-environment-variables) in #52 - please reopen if I'm wrong.
